### ISSUE TITLE
twisted.internet.error.ReactorNotRunning

### ISSUE THREAD

**Issue by stefexec** [JLyne/LinkingServer#1]
Hey, i've compiled the latest version for 1.19.2 but i get thrown an exception. 

> 15.08 13:57:24 [Server] INFO Unhandled Error
> 15.08 13:57:24 [Server] INFO Traceback (most recent call last):
> 15.08 13:57:24 [Server] INFO File "linkingserver/__main__.py", line 64, in <module>
> 15.08 13:57:24 [Server] INFO File "site-packages/twisted/internet/base.py", line 1315, in run
> 15.08 13:57:24 [Server] INFO File "site-packages/twisted/internet/base.py", line 1325, in mainLoop
> 15.08 13:57:24 [Server] INFO --- <exception caught here> ---
> 15.08 13:57:24 [Server] INFO File "site-packages/twisted/internet/base.py", line 964, in runUntilCurrent
> 15.08 13:57:24 [Server] INFO File "site-packages/twisted/internet/base.py", line 708, in stop
> 15.08 13:57:24 [Server] INFO twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

I've fiddled around for a few hours but i can't seem to find the issue. I'd be very glad for your help or a toss in the right direction. Thanks.

**Comment by stefexec** [comment]
Server restart fixed the issue.
